---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build Landing Page Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  STAGE: dev

jobs:
  build-landing-page-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 900

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Yarn Install Landing Page
        run: yarn install

      - name: Build Landing Page
        run: yarn build:${STAGE}
