---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build Landing Page Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  STAGE: dev

permissions:
  contents: read
  id-token: write

jobs:
  build-landing-page-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::395594542180:role/github-actions-deploy
          aws-region: us-east-1

      - name: Yarn Install Landing Page
        run: yarn install

      - name: Build Landing Page
        run: yarn build:${STAGE}
