---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build and Deploy DEV

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  STAGE: dev

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::395594542180:role/github-actions-deploy
          aws-region: us-east-1

      - name: Setup
        run: yarn install

      - name: Build Landing Page
        run: |
          yarn prebuild:${STAGE}
          yarn build:${STAGE}
          
      - name: Deploy Landing Page to DEV
        run: |
          echo "Deploying backend for stage ${STAGE} in region ${AWS_REGION}"
          SLS_DEBUG=* ./node_modules/serverless/bin/serverless.js deploy -s ${STAGE} -r ${AWS_REGION} --verbose
    
          SLS_DEBUG=* ./node_modules/serverless/bin/serverless.js client deploy -s ${STAGE} -r ${AWS_REGION} --no-confirm --no-policy-change --no-config-change
    
          # Use AWS CLI to invalidate the CloudFront cache - the serverless plugin was causing some incompatibilities between node and the config
          echo "Invalidating Cloudfront caches using command: aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'"

          # SLS_DEBUG=* ./node_modules/serverless/bin/serverless.js cloudfrontInvalidate -s ${STAGE} -r ${AWS_REGION} --cloudfront=true
          aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
        env:
          DISTRIBUTION_ID: E4CMSMNLN6Y7T
